In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4,5])

In [3]:
x

array([1, 2, 3, 4, 5])

In [4]:
y = np.array([[1,2],[3,4],[5,6]])

In [5]:
y

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
x[0]

1

In [7]:
y[1,1]

4

In [8]:
x.shape

(5,)

In [9]:
y.shape

(3, 2)

In [10]:
y.shape[0], y.shape[1]

(3, 2)

In [11]:
len(y.shape)

2

In [12]:
y

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
y.reshape(6)

array([1, 2, 3, 4, 5, 6])

In [14]:
y.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [15]:
y.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
y.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
x2 = np.array([1,2,3,4,5,6])

In [18]:
x2.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
x2.reshape(3,-1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
y

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
y[:,0]

array([1, 3, 5])

In [22]:
y[0:2,0]

array([1, 3])

In [23]:
y[0:2,:]

array([[1, 2],
       [3, 4]])

In [24]:
y[:,-1]

array([2, 4, 6])

In [25]:
y[-1,:]

array([5, 6])

In [26]:
y[-1,1]

6

In [27]:
z = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [28]:
z2 = z.reshape(3,4)

In [29]:
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [30]:
z2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
z2[0:2, 1:3]

array([[2, 3],
       [6, 7]])

In [32]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [33]:
a + b

array([5, 7, 9])

In [34]:
a - b

array([-3, -3, -3])

In [35]:
a * b

array([ 4, 10, 18])

In [36]:
a / b

array([0.25, 0.4 , 0.5 ])

In [37]:
a + 100

array([101, 102, 103])

In [38]:
a - 100

array([-99, -98, -97])

In [39]:
a * 100

array([100, 200, 300])

In [40]:
a / 100

array([0.01, 0.02, 0.03])

In [41]:
a**2

array([1, 4, 9], dtype=int32)

In [42]:
o = np.array([1,2])

In [43]:
# a+o

In [44]:
z2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
np.sqrt(z2)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [46]:
np.sin(z2)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825],
       [ 0.41211849, -0.54402111, -0.99999021, -0.53657292]])

In [47]:
np.cos(z2)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362],
       [ 0.28366219,  0.96017029,  0.75390225, -0.14550003],
       [-0.91113026, -0.83907153,  0.0044257 ,  0.84385396]])

In [48]:
np.exp(z2)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

In [49]:
np.tan(z2)

array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
         1.15782128e+00],
       [-3.38051501e+00, -2.91006191e-01,  8.71447983e-01,
        -6.79971146e+00],
       [-4.52315659e-01,  6.48360827e-01, -2.25950846e+02,
        -6.35859929e-01]])

In [50]:
np.tanh(z2)

array([[0.76159416, 0.96402758, 0.99505475, 0.9993293 ],
       [0.9999092 , 0.99998771, 0.99999834, 0.99999977],
       [0.99999997, 1.        , 1.        , 1.        ]])

In [51]:
np.floor(np.exp(z2))

array([[2.00000e+00, 7.00000e+00, 2.00000e+01, 5.40000e+01],
       [1.48000e+02, 4.03000e+02, 1.09600e+03, 2.98000e+03],
       [8.10300e+03, 2.20260e+04, 5.98740e+04, 1.62754e+05]])

In [52]:
np.ceil(np.exp(z2))

array([[3.00000e+00, 8.00000e+00, 2.10000e+01, 5.50000e+01],
       [1.49000e+02, 4.04000e+02, 1.09700e+03, 2.98100e+03],
       [8.10400e+03, 2.20270e+04, 5.98750e+04, 1.62755e+05]])

In [53]:
z2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [54]:
z2.sum(axis=0)

array([15, 18, 21, 24])

In [55]:
z2.sum(0)

array([15, 18, 21, 24])

In [56]:
z2.sum(1)

array([10, 26, 42])

In [57]:
z2.mean(1)

array([ 2.5,  6.5, 10.5])

In [58]:
z2.mean(0)

array([5., 6., 7., 8.])

In [59]:
z2.prod(0)

array([ 45, 120, 231, 384])

In [60]:
z2.std(0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [62]:
z2.var(0)

array([10.66666667, 10.66666667, 10.66666667, 10.66666667])