In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4,5])

In [3]:
x

array([1, 2, 3, 4, 5])

In [4]:
y = np.array([[1,2],[3,4],[5,6]])

In [5]:
y

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
x[0]

1

In [7]:
y[1,1]

4

In [8]:
x.shape

(5,)

In [9]:
y.shape

(3, 2)

In [10]:
y.shape[0], y.shape[1]

(3, 2)

In [11]:
len(y.shape)

2

In [12]:
y

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
y.reshape(6)

array([1, 2, 3, 4, 5, 6])

In [14]:
y.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [15]:
y.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
y.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
x2 = np.array([1,2,3,4,5,6])

In [18]:
x2.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
x2.reshape(3,-1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
y

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
y[:,0]

array([1, 3, 5])

In [22]:
y[0:2,0]

array([1, 3])

In [23]:
y[0:2,:]

array([[1, 2],
       [3, 4]])

In [24]:
y[:,-1]

array([2, 4, 6])

In [25]:
y[-1,:]

array([5, 6])

In [26]:
y[-1,1]

6

In [28]:
z = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [31]:
z2 = z.reshape(3,4)

In [30]:
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [32]:
z2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
z2[0:2, 1:3]

array([[2, 3],
       [6, 7]])